import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center mt-5">
          <div className="w-full">
            <div className="hidden sm:block">
              <div className="border-b border-gray-200">
                <nav className="flex justify-center gap-10" aria-label="Tabs">
                  <Link
                    href="/"
                    className="shrink-0 border-b-2 border-transparent px-1 pb-4 text-base font-medium text-gray-500 hover:border-sky-300 hover:text-sky-700"
                  >
                    Inicio
                  </Link>

                  <Link
                    href="/Login"
                    className="shrink-0 border-b-2 border-transparent px-1 pb-4 text-base font-medium text-gray-500 hover:border-sky-300 hover:text-sky-700"
                  >
                    Login
                  </Link>

                  <Link
                    href="/Register"
                    className="shrink-0 border-b-2 border-transparent px-1 pb-4 text-base font-medium text-gray-500 hover:border-sky-300 hover:text-sky-700"
                  >
                    Registro
                  </Link>
                </nav>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
